
name: pg client dev

on:
    workflow_dispatch:
    push:
        branches:
          - 'main'
          - 'support/**'
        paths-ignore:
          - README.md
          - LICENSE

env:
  SUPPORT_VERSION: "14"
  
jobs:
    linter:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code.
              uses: actions/checkout@v4

            - name: Dockerfile linter
              uses: luke142367/Docker-Lint-Action@v1.1.1
              with:
                  dockerfile: Dockerfile
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code.
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build the Docker image
              uses: docker/build-push-action@v6
              id: docker_build
              with:
                  push: true
                  tags: piccio/aa-pg-client:${{ env.SUPPORT_VERSION }}-${{ github.sha }}

    security:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code.
              uses: actions/checkout@v4

            - name: Trivy scan
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: 'piccio/aa-pg-client:${{ env.SUPPORT_VERSION }}-${{ github.sha }}'
                  format: 'template'
                  template: '@/contrib/sarif.tpl'
                  output: 'trivy-results.sarif'
                  severity: 'CRITICAL,HIGH,MEDIUM,LOW'
        
            - name: Upload Trivy scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v3
              with:
                  sarif_file: 'trivy-results.sarif'
