
name: pg client

on:
    workflow_dispatch:
    push:
        branches:
            - 'main'
            - 'support/**'

jobs:
    linter:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code.
              uses: actions/checkout@v4

            - name: Dockerfile linter
              uses: luke142367/Docker-Lint-Action@v1.1.1
              with:
                  dockerfile: Dockerfile
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code.
              uses: actions/checkout@v4

            - name: Build the Docker image
              uses: docker/build-push-action@v6
              id: docker_build
              with:
                  push: true
                  tags: piccio/aa-pg-client:${{ github.ref_name }}

    security:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code.
              uses: actions/checkout@v4

            - name: Trivy scan
              uses: aquasecurity/trivy-action@master
              with:
                  image-ref: 'piccio/aa-pg-client:${{ github.ref_name }}'