
name: pg client

on:
    workflow_dispatch:
    push:
        branches:
            - 'main'
            - 'support/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code.
              uses: actions/checkout@v4
            - name: Dockerfile linter
              uses: luke142367/Docker-Lint-Action@v1.1.1
              with:
                  dockerfile: Dockerfile
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build the Docker image
              uses: docker/build-push-action@v6
              id: docker_build
              with:
                  push: true
                  tags: piccio/aa-pg-client:0.0.0-${{ github.ref_name}}
