name: nightly ci

on:
    schedule:
        - cron: '0 0 * * *'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code. 
              uses: actions/checkout@v4
            - name: Build
              run: |
                  yarn install
                  yarn build