name: pg client nightly ci

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code.
              uses: actions/checkout@v4
              with:
                  ref: support/16

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build the Docker image
              uses: docker/build-push-action@v6
              id: docker_build
              with:
                  push: true
                  tags: piccio/aa-pg-clients:${{ github.ref_name }}-nightly

    security:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code.
              uses: actions/checkout@v4

            - name: Trivy scan
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: 'piccio/aa-pg-clients:${{ github.ref_name }}'
                format: 'template'
                template: '@/contrib/sarif.tpl'
                output: 'trivy-results.sarif'
                severity: 'CRITICAL,HIGH,MEDIUM,LOW'
      
            - name: Upload Trivy scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v3
              with:
                sarif_file: 'trivy-results.sarif'
