
name: pg client release

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code.
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build the Docker image
              uses: docker/build-push-action@v6
              id: docker_build
              with:
                  push: true
                  tags: piccio/aa-pg-client:${{ github.ref_name }}
